---
- hosts: all
  become: no

  environment:
    REACT_APP_ENV: prod

  tasks:
    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Install serve
      npm:
        name: serve
        global: yes

    - name: Clone the repository
      git:
        repo: git@github.com:jhonber/codechef-virtual-contest.git
        dest: /root/deploy
        accept_hostkey: yes
        force: yes

    - name: Install project dependencies
      npm:
        path: /root/deploy

    - name: Build static site
      command: npm run build
      args:
        chdir: /root/deploy

    - name: Delete old pm2 process
      command: pm2 delete frontend
      ignore_errors: yes

    - name: Start frontend using pm2
      command: pm2 start /usr/local/bin/serve --name frontend -- /root/deploy/build -l 80 -c /root/deploy/serve.json